### ISSUE TITLE
Why the new repo?

### ISSUE THREAD

**Issue by jnewbery** [coredev-tech/coredev-tech.github.io#1]
Any reason not to keep using the old https://github.com/coredev-tech/coredev-dot-tech repo and just enable github pages there? Or rename that repo?

If neither of those are possible, can we at least keep the git history?

**Comment by jonasschnelli** [comment]
Maybe a rename would have worked. I wasn't sure so just created a new one.
I just imported the file from the running host.

Isn't it enough to keep the old repository in read only mode? I don't think the history is super important (we keep infos of the old events anyways).

**Comment by jonasschnelli** [comment]
Ah. Maybe the authorship of the files... yeah. Let me see if I can use the old repo git and import it here.

**Comment by jnewbery** [comment]
I can't see any downside to continue using the old repo: it means contributors don't need to all delete their local repos and create new ones, and keeps the author history.

**Comment by jonasschnelli** [comment]
I wasn't aware that you can rename an existing repository to enable GitHub Pages (I'm still not sure if this works but probably will).

I just pushed the old git and it seems to run well.

**Comment by jnewbery** [comment]
Thanks!
